### ISSUE TITLE
[NEOS-582] Create compose file that uses production images

### ISSUE THREAD

**Issue by nickzelei** [nucleuscloud/neosync#1004]
Today the compose file requires building dev docker images.

It would be great to have one that uses the production images so people can just `docker pull && docker compose up -d`

<sub>From [SyncLinear.com](https://synclinear.com) | [NEOS-582](https://linear.app/nucleus-cloud/issue/NEOS-582/create-compose-file-that-uses-production-images)</sub>

**Comment by faisalill** [comment]
@nickzelei 
I will take this up.
