### ISSUE TITLE
Terms of Service and Privacy Policy redirect to a 404

### ISSUE THREAD

**Issue by flowck** [nucleuscloud/neosync#1021]
FYI: The two pages are referenced on the website's footer.

Cheers,
Firmino

![Screenshot 2024-01-02 at 22 56 42](https://github.com/nucleuscloud/neosync/assets/1679333/a952de97-f0f4-4334-9dfb-ac4ff5670892)

![Screenshot 2024-01-02 at 22 56 49](https://github.com/nucleuscloud/neosync/assets/1679333/cc3497ab-5a26-4af5-9a66-695db07933ea)

**Comment by nickzelei** [comment]
whoops, good call out. We'll get this addressed. Thank you!

**Comment by evisdrenova** [comment]
thanks for calling this out! this has been resolved in [#1034](https://github.com/nucleuscloud/neosync/pull/1034)
