### ISSUE TITLE
[NEOS-627] Add markdownlint for md files

### ISSUE THREAD

**Issue by nickzelei** [nucleuscloud/neosync#1093]
[https://github.com/DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)

Would be great to have this lint our markdown files. Helps catch spellchecks and can enforce other design constraints, etc.

This will be especially useful for the docs 

<sub>From [SyncLinear.com](https://synclinear.com) | [NEOS-627](https://linear.app/nucleus-cloud/issue/NEOS-627/add-markdownlint-for-md-files)</sub>

**Comment by danieltayal07** [comment]
hii
i am interested in contributing in this as hacktoberfest2024,
if you could please assign me this 
and add hacktoberfest2024 and hacktoberfest-accepted tag in the issue
