### ISSUE TITLE
[NEOS-694] Provide ability to source neosync-api database password from an existing secret in helm chart

### ISSUE THREAD

**Issue by nickzelei** [nucleuscloud/neosync#1229]
Would be great to have the database password live in a separate secret that we can source via the kubernetes deployment.

would need to add support for this in the helm chart.

<sub>From [SyncLinear.com](https://synclinear.com) | [NEOS-694](https://linear.app/nucleus-cloud/issue/NEOS-694/provide-ability-to-source-neosync-api-database-password-from-an)</sub>

**Comment by joshgubler** [comment]
I'd love for this request to be reopened. We use a GitOps deployment methodology and Hashicorp Vault as an enterprise secrets manager. Having to embed database passwords in the values.yaml file which is committed to the Git repository is not an acceptable requirement. If the password could be pulled from a pre-existing secret, we could use our standard pattern of managing that secret with a VaultStaticSecret resource.
