### ISSUE TITLE
[NEOS-707] change column header from action to logs in job details page

### ISSUE THREAD

**Issue by evisdrenova** [nucleuscloud/neosync#1245]
![image.png](https://uploads.linear.app/a9c4e27b-39a0-41a6-a85a-a5e6b97b33a2/dce6e977-9345-462e-bb78-8001ed3cacfe/6bcf3be0-8114-490d-a9cd-a91229b68a63?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2E5YzRlMjdiLTM5YTAtNDFhNi1hODVhLWE1ZTZiOTdiMzNhMi9kY2U2ZTk3Ny05MzQ1LTQ2MmUtYmI3OC04MDAxZWQzY2FjZmUvNmJjZjNiZTAtODExNC00OTBkLWE5Y2QtYTkxMjI5YjY4YTYzIiwiaWF0IjoxNzA2NzMwODk3LCJleHAiOjE3MDY4MTcyOTd9.y8Lm6FyPwvAKNLGRSN2knaswKaRsJIHgQRgs72m1GWA)

today it just goes to logs so lets make it more clear by naming the column 'Logs'

<sub>From [SyncLinear.com](https://synclinear.com) | [NEOS-707](https://linear.app/nucleus-cloud/issue/NEOS-707/change-column-header-from-action-to-logs-in-job-details-page)</sub>

**Comment by nickzelei** [comment]
Idk if `logs` is the right thing here. That action takes you to the job run itself. The url is `/runs/:id` 
It might be better to just not have a name in that column at all. I think we do that in a few other spots.

**Comment by nickzelei** [comment]
OTOH, the runid column is clickable. We could potentially just drop that column entirely..unless we wanted to update it to be like our other tables and have it pop up a context menu to `View` or `Delete`. That would be more consistent with pretty much all of our other tables.

**Comment by evisdrenova** [comment]
Yeah we could drop it but the run id is not obviously clickable unless you hover over it so a user might not realize that they can click on it. The arrow is at least pretty clear that you can take an action on it. IMO 'Logs' or 'Details' or something like that makes the most sense. Unless we allow users to delete the run from this table then idk if the View & Delete make sense.

**Comment by nickzelei** [comment]
Well that's what I'm getting at. The right thing to do here might be to update that column to be like the other tables and surface a View and Delete button.

**Comment by nickzelei** [comment]
pasting some examples here to get a clear idea of what the state of our app currently is. 

![image.png](https://uploads.linear.app/a9c4e27b-39a0-41a6-a85a-a5e6b97b33a2/fc0c6ad4-d8ac-41cd-8451-bda1261a199b/f3e60b3e-dc2d-4789-b43f-776775e485c4)

![image.png](https://uploads.linear.app/a9c4e27b-39a0-41a6-a85a-a5e6b97b33a2/ccba6865-9cd4-4989-a927-e18200d223a6/4ceee98f-465e-4119-9d36-428d132ba897)

![image.png](https://uploads.linear.app/a9c4e27b-39a0-41a6-a85a-a5e6b97b33a2/8166464f-e033-4bb0-8162-b414e4a50b6a/8e398442-85e2-49cf-9414-42d691feae00)

![image.png](https://uploads.linear.app/a9c4e27b-39a0-41a6-a85a-a5e6b97b33a2/cbac0f69-4622-4a6d-a93a-99a6ac82df2a/9e1215d6-546d-44a5-9c38-65f4bc509be7)

**Comment by evoxf1** [comment]
May I try @nickzelei

**Comment by evoxf1** [comment]
> pasting some examples here to get a clear idea of what the state of our app currently is.
> 
> ![image.png](https://camo.githubusercontent.com/7248b730e622cf51292cad5556018f4efc792d980194643ce16b34624ae9d8b9/68747470733a2f2f75706c6f6164732e6c696e6561722e6170702f61396334653237622d333961302d343161362d613835612d6135653662393762333361322f66633063366164342d643861632d343163642d383435312d6264613132363161313939622f66336536306233652d646332642d343738392d623433662d373736373735653438356334)
> 
> ![image.png](https://camo.githubusercontent.com/ad6e3f664c7e6d8157255d87f5b845c4d0fdb4c50f62a11073a671974787b0a8/68747470733a2f2f75706c6f6164732e6c696e6561722e6170702f61396334653237622d333961302d343161362d613835612d6135653662393762333361322f63636261363836352d396364342d343938392d613932372d6531383230306432323361362f34636565653938662d343635652d343131392d396433362d343238643133326261383937)
> 
> ![image.png](https://camo.githubusercontent.com/d5466be0a0b79f12bd536c76d038ed887b21c912cce05b7c43ddbdb691a71cc3/68747470733a2f2f75706c6f6164732e6c696e6561722e6170702f61396334653237622d333961302d343161362d613835612d6135653662393762333361322f38313636343634662d653033332d346262302d383136322d6234313465346135306236612f38653339383434322d383565322d343963662d393431342d343264363931666561653030)
> 
> ![image.png](https://camo.githubusercontent.com/1cfdc3820bd8e49e95b478d287fd8c1a3af1940a9f760635134b1982fd79066f/68747470733a2f2f75706c6f6164732e6c696e6561722e6170702f61396334653237622d333961302d343161362d613835612d6135653662393762333361322f63626163306636392d343632322d346136642d613933612d3939613661633832646632612f39653132313564362d353436642d343461352d396333382d363566346263353039626537)

no image is visible!!!!
![image](https://github.com/nucleuscloud/neosync/assets/109587708/61b94a6d-126f-4342-b5f7-3f25d86ad60b)

**Comment by evisdrenova** [comment]
@evoxf1 ah they must not have copied over from linear, here are the examples:

![image](https://github.com/nucleuscloud/neosync/assets/80707987/25d3c4b4-ec35-4509-baa3-8eba9283b286)
![image](https://github.com/nucleuscloud/neosync/assets/80707987/e998b446-5b6b-47b3-9db6-42d59afd98be)
![image](https://github.com/nucleuscloud/neosync/assets/80707987/ec0bb170-b419-429d-8485-f40577ff0540)

Here's a quick plan for this:
1. For this, we'll just want keep the column named as "Actions" but update the arrow to be a drop down (the three vertical dots as you see in the screenshots) that have the options available in a drop down that you see in a Job Run Details i.e.  Delete, Cancel, Terminate. So we'll want to render those options in the drop down. 
2. For the delete, we have a component called the <DeleteConfirmationDialog /> that already has most of the logic built out for the delete, you'll just have to pass in a `onDelete()` async function that actually does the delete. There's a bunch of examples of this if you search for <DeleteConfirmationDialog />. 
3. Lastly, tthe job run options i.e. cancel and terminate are only availble while the job is running, otherwise, it's the only option is delete. So you'll need to make sure you account for conditionally rendering those options only while the job is running. You can check out how we do this in the Job run details page at `runs/[id]/page.tsx`, specifically this part:
`{(jobRun?.status === JobRunStatusEnum.RUNNING ||
                jobRun?.status === JobRunStatusEnum.PENDING) && (
                <div className="flex flex-row gap-4">
                  <ConfirmationDialog
                    trigger={
                      <Button variant="default">
                        <ButtonText leftIcon={<Cross2Icon />} text="Cancel" />
                      </Button>
                    }
                    headerText="Are you sure you want to cancel this job run?"
                    description=""
                    onConfirm={async () => onCancel()}
                    buttonText="Cancel"
                    buttonVariant="default"
                    buttonIcon={<Cross2Icon />}
                  />
                  <ConfirmationDialog
                    trigger={
                      <Button>
                        <ButtonText leftIcon={<TiCancel />} text="Terminate" />
                      </Button>
                    }
                    headerText="Are you sure you want to terminate this job run?"
                    description=""
                    onConfirm={async () => onTerminate()}
                    buttonText="Terminate"
                    buttonVariant="default"
                    buttonIcon={<Cross2Icon />}
                  />
                </div>
              )}`

Lmk if you have any questions and thanks!!

**Comment by evoxf1** [comment]
@evisdrenova sorry I got lost in my personal issues, will look into this now probably :)

**Comment by evisdrenova** [comment]
@evoxf1 no worries!
