### ISSUE TITLE
Error when running make compose-up

### ISSUE THREAD

**Issue by charlievc** [nucleuscloud/neosync#1352]
## Bug description
Getting this error `services.api.depends_on.db Additional property restart is not allowed` when trying to run the make compose-up command.

*Please describe.*
<img width="386" alt="image" src="https://github.com/nucleuscloud/neosync/assets/53860265/dfb8dd0a-8436-43cf-a7dd-ba260c84a8cd">

## How to reproduce

1. clone neosync main branch
2. ensure docker is open
3. run `make compose-up`
4. error encountered

## Environment
dev local env

## Additional context
n/a

**Comment by nickzelei** [comment]
Interesting, I'm not able to reproduce this. I ran `make compose-up` and my services started.
Maybe a version or environment difference?

Either way, I did a little research and it seems like this error is valid because restart doesn't belong there anyways. I'll cut a PR to remove it from the compose files.

**Comment by nickzelei** [comment]
Strike that, I found the article in docker where this is indeed valid syntax: https://docs.docker.com/compose/compose-file/05-services/#long-syntax-1

Example from their codebase:

**Comment by nickzelei** [comment]
@charlievc 
What version of docker and compose are you running?
This is what I have:
```
➜  neosync git:(main) docker --version
Docker version 24.0.6-rd, build da4c87c
➜  neosync git:(main) docker compose version
Docker Compose version v2.23.3-desktop.2
```

**Comment by charlievc** [comment]
thanks so much for your investigations @nickzelei. you are right, its my docker version. the services are now running... THANK YOU!

**Comment by nickzelei** [comment]
Glad to hear it!! Happy to help.
