### ISSUE TITLE
make: *** [compose-up] Error 125

### ISSUE THREAD

**Issue by iOrevir** [nucleuscloud/neosync#1480]
## Bug description

When launching the app with `make compose-up` the following error appears `make: *** [compose-up] Error 125`

## How to reproduce

1. clone repo
2. move to root directory
3. run `make compose-up`

## Environment
zsh (Mac OS)
Docker version 25.0.3, build 4debf41 

## Additional context
na

**Comment by nickzelei** [comment]
Closed via #1481
