### ISSUE TITLE
[NEOS-945] Remove functionality for omitting a table if all columns are null

### ISSUE THREAD

**Issue by nickzelei** [nucleuscloud/neosync#1670]
This made sense before as a way to omit a table when we required the full database.

Now that we support partial syncs, we should actually set every column to null.

This was a hidden feature, now it's just a bug.

<sub>From [SyncLinear.com](https://synclinear.com) | [NEOS-945](https://linear.app/nucleus-cloud/issue/NEOS-945/remove-functionality-for-omitting-a-table-if-all-columns-are-null)</sub>

**Comment by evisdrenova** [comment]
looks like for the gen jobs its in the benthos-builder.go file at lines 729

```
		if shared.AreAllColsNull(tableMapping.Mappings) {
			// skiping table as no columns are mapped
			continue
		}
```
