### ISSUE TITLE
[NEOS-1065] Benthos Error Process Handler not surfacing correct error

### ISSUE THREAD

**Issue by evisdrenova** [nucleuscloud/neosync#1901]
i got this error when I was trying to generate an email address: 

![image.png](https://uploads.linear.app/a9c4e27b-39a0-41a6-a85a-a5e6b97b33a2/b5ad7a92-7814-44c1-86a0-9bba9798bc89/9dbd9071-0d3c-4959-9a9b-756d30ddfdf1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2E5YzRlMjdiLTM5YTAtNDFhNi1hODVhLWE1ZTZiOTdiMzNhMi9iNWFkN2E5Mi03ODE0LTQ0YzEtODZhMC05YmJhOTc5OGJjODkvOWRiZDkwNzEtMGQzYy00OTU5LTlhOWItNzU2ZDMwZGRmZGYxIiwiaWF0IjoxNzE0NzU0NjY3LCJleHAiOjE3MTQ4NDEwNjd9.7RyTBWxAH42fwR5XI8W7JavpHqf4ZMNpkXLVi8E-aCc)

and in the worker the error is:

![image.png](https://uploads.linear.app/a9c4e27b-39a0-41a6-a85a-a5e6b97b33a2/249dac43-01d3-4909-8741-dbd1073f3743/3b2f7f4f-d285-4278-bebe-750ef41bdcd4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2E5YzRlMjdiLTM5YTAtNDFhNi1hODVhLWE1ZTZiOTdiMzNhMi8yNDlkYWM0My0wMWQzLTQ5MDktODc0MS1kYmQxMDczZjM3NDMvM2IyZjdmNGYtZDI4NS00Mjc4LWJlYmUtNzUwZWY0MWJkY2Q0IiwiaWF0IjoxNzE0NzU0NjY3LCJleHAiOjE3MTQ4NDEwNjd9.VoTwQkfPOpc2zXpC-5QSCECQDThQHgVv0EJ10QFeY0g)

 i think we need a better way to return the error here because just returning "null" isn't enough for the user to go off of which emans they have to dig through the worker logs which isn't a great experience

<sub>From [SyncLinear.com](https://synclinear.com) | [NEOS-1065](https://linear.app/nucleus-cloud/issue/NEOS-1065/benthos-error-process-handler-not-surfacing-correct-error)</sub>

**Comment by evisdrenova** [comment]
```
neosync-worker  | {"time":"2024-05-03T16:22:15.743260422Z","level":"ERROR","msg":"failed assignment (line 4): function 'generate_email': failed to extract input arg 'email_type': wrong argument type, expected string, got null","metadata":{"Schema":"public","Table":"users"},"WorkflowID":"1f9534d3-34e9-4dd8-99d1-66e89a471182-2024-05-03T16:22:15Z","RunID":"42b3bc80-4b0b-455e-9a45-85294835db3f","activitySession":"4cfccdb7-dc46-4cf6-ab8a-240168f9cf98","benthos":"true","path":"root.output","label":"","path":"root.output.broker","path":"root.output.broker.outputs","path":"root.output.broker.outputs.0","label":"","path":"root.output.broker.outputs.0.fallback","path":"root.output.broker.outputs.0.fallback","path":"root.output.broker.outputs.0.fallback.0","label":"","path":"root.output.broker.outputs.0.fallback.0.retry","path":"root.output.broker.outputs.0.fallback.0.retry.output","label":"","path":"root.output.broker.outputs.0.fallback.0.retry.output.processors.0","label":""}
neosync-worker  | {"time":"2024-05-03T16:22:15.743265088Z","level":"ERROR","msg":"Benthos Error processor - sending stop activity signal: null ","metadata":{"Schema":"public","Table":"users"},"WorkflowID":"1f9534d3-34e9-4dd8-99d1-66e89a471182-2024-05-03T16:22:15Z","RunID":"42b3bc80-4b0b-455e-9a45-85294835db3f","activitySession":"4cfccdb7-dc46-4cf6-ab8a-240168f9cf98","benthos":"true","path":"root.output","label":"","path":"root.output.broker","path":"root.output.broker.outputs","path":"root.output.broker.outputs.0","label":"","path":"root.output.broker.outputs.0.fallback","path":"root.output.broker.outputs.0.fallback","path":"root.output.broker.outputs.0.fallback.0","label":"","path":"root.output.broker.outputs.0.fallback.0.retry","path":"root.output.broker.outputs.0.fallback.0.retry.output","label":"","path":"root.output.broker.outputs.0.fallback.0.retry.output.processors.1","label":"","path":"root.output.broker.outputs.0.fallback.0.retry.output.processors.1.catch","path":"root.output.broker.outputs.0.fallback.0.retry.output.processors.1.catch","path":"root.output.broker.outputs.0.fallback.0.retry.output.processors.1.catch.0","label":""}
```

more logs.
This is a bug or our mishandling of the processor_error plugin we have if there is an error in the processor. We need to do more work here to surface the actual error we're finding in the processor, as the error message we get back from benthos is a string that just says `null`

**Comment by nickzelei** [comment]
Separately to this, I'm shocked that the bloblang parser passed when the strings weren't quoted for the email_type, as that fixed it. Strings don't necessarily need quoted for yaml, so there must be a failure somewhere else as it went away when I made them quoted. Should dive deeper into this error (which will also help us debug this process error) and then write a test that catches more instances of this in the future.

**Comment by nickzelei** [comment]
The fix for this is here in this PR: [https://github.com/nucleuscloud/neosync/pull/1907](https://github.com/nucleuscloud/neosync/pull/1907)
Turns out the bloblang.Parse only checks for lints, we have to actually query it so that it tries to compile the interpolated string against real values, which is where it ends up failing. I've added this assertion to our compute mutation method so that in the future as we update that method with new params, the test will fail so we can catch this stuff at unit test time.
