### ISSUE TITLE
[NEOS-1095] update docker compose scripts to check for open ports

### ISSUE THREAD

**Issue by evisdrenova** [nucleuscloud/neosync#1964]
ran into an port issue when i ran `docker compose -f compose.dev.yml` because it was trying to stand up a db on `5435` but I was already using that port. Chris from Osmind had some of the same feedback when he was trying to stand us up locally - he had conflicts with an existing set up.

![image.png](https://uploads.linear.app/a9c4e27b-39a0-41a6-a85a-a5e6b97b33a2/50dbdadc-9631-4051-97bc-1efc7ba1c5e4/50cc1a1d-ebf7-4d10-ac28-0396985586b2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2E5YzRlMjdiLTM5YTAtNDFhNi1hODVhLWE1ZTZiOTdiMzNhMi81MGRiZGFkYy05NjMxLTQwNTEtOTdiYy0xZWZjN2JhMWM1ZTQvNTBjYzFhMWQtZWJmNy00ZDEwLWFjMjgtMDM5Njk4NTU4NmIyIiwiaWF0IjoxNzE1NzExMzQ1LCJleHAiOjE3NDcyNDczNDV9.nkXT3K7VUNdKKDWLyB0f7hTXxnFfD0NdeSjh26KnrUk)

Would be nice to be able to continue to search for a port if it finds the first port is already allocated, a better user experience compared to the user having to go and update things. For me, I already had a DB that I was actively using on that port so it was annoying to have to update it to use a new port for the docker compose would work.

we can run an init script before any of the containers are created to check what ports are open and then dynamically update the following scripts with those ports. Would have to make sure that we also update the seed scripts with the right port number as well.

<sub>From [SyncLinear.com](https://synclinear.com) | [NEOS-1095](https://linear.app/nucleus-cloud/issue/NEOS-1095/update-docker-compose-scripts-to-check-for-open-ports)</sub>

**Comment by nickzelei** [comment]
I hear you on the open ports thing, however I think this is way more complex than it's worth.
A much simpler solution is to just change our default ports to something else.


Many examples on the internet use these ports which is why it is a conflict.

**Comment by evisdrenova** [comment]
yeah agreed - might be nice to use some non-standard ports to try and avoid the issue…. until someone is using those ports 😅
