### ISSUE TITLE
Scan error on column index 7, name \"character_maximum_length\"

### ISSUE THREAD

**Issue by kdouda** [nucleuscloud/neosync#2052]
## Bug description

Hello! I ran into a bug when trying the system out against a MariaDB database. Connection is successful, but once I start a sync job from a remote database to my local instance, I run into an error.

{
    "message": "[unknown] sql: Scan error on column index 7, name \"character_maximum_length\": converting driver.Value type uint64 (\"4294967295\") to a int32: value out of range"
}

We don't have this column in our database - it might be something related to the information schema. It's a bit cryptic, since it doesn't say the name of the table. All the API calls produce this issue with no further detail.

## How to reproduce

It might not be easily reproducible - just a general pointer or improving the error message would be helpful.

## Environment

docker-compose from this repository running locally (MacOS)
10.11.7-MariaDB-1:10.11.7+maria~deb11

character-set-server  = utf8mb4
collation-server      = utf8mb4_general_ci

**Comment by nickzelei** [comment]
Hi there, I believe I fixed this bug already here: https://github.com/nucleuscloud/neosync/pull/2025
However, I haven't cut a new release yet. I can do that now so it's in the latest tag!

**Comment by kdouda** [comment]
Thank you! I'll try it asap. Sorry for making a duplicate!
