### ISSUE TITLE
[NEOS-1215] Add github action that fails if go mod tidy results in git changes

### ISSUE THREAD

**Issue by nickzelei** [nucleuscloud/neosync#2223]
We shouldn't allow checking in a go.mod that needs to be tidied.

We can easily add a github action that checks this.

<sub>From [SyncLinear.com](https://synclinear.com) | [NEOS-1215](https://linear.app/nucleus-cloud/issue/NEOS-1215/add-github-action-that-fails-if-go-mod-tidy-results-in-git-changes)</sub>

**Comment by karimalzalek** [comment]
Hello @nickzelei , would suggest adding to go.yml under (.github/workflows)
Will fork and submit a PR for your review.
