### ISSUE TITLE
[NEOS-1237] Add github action that prevents merge on unlabeled PRs

### ISSUE THREAD

**Issue by nickzelei** [nucleuscloud/neosync#2294]
We should have a job that runs on a pull request that does not contain any labels (or maybe just always runs).

Then we can add a condition that it is unmergeable if it does not have a label attached.

We might need it to run all the time os that we can can "require" the test be passing before it is considered mergeable.

Could maybe be used as a reference: [https://stackoverflow.com/questions/71502652/prevent-merging-of-branch-conditionally-based-on-label](https://stackoverflow.com/questions/71502652/prevent-merging-of-branch-conditionally-based-on-label)

This way it forces us to label or PRs so that they are better associated in our changelog.

<sub>From [SyncLinear.com](https://synclinear.com) | [NEOS-1237](https://linear.app/nucleus-cloud/issue/NEOS-1237/add-github-action-that-prevents-merge-on-unlabeled-prs)</sub>

**Comment by frankie-mur** [comment]
Heya @nickzelei , I could take this on 🫡

**Comment by nickzelei** [comment]
> Heya @nickzelei , I could take this on 🫡

Sounds good!
