### ISSUE TITLE
[NEOS-1311] syntax error: NeosyncAddIndexIfNotExists

### ISSUE THREAD

**Issue by b3nk3** [nucleuscloud/neosync#2424]
## Bug description

I'm trying to sync a Strapi mysql DB using the local docker setup. For testing purposes I have set all tables/columns to `passthrough`.

With these settings: 
![CleanShot 2024-08-06 at 11 15 40](https://github.com/user-attachments/assets/453d111f-b687-41d7-9751-fa6272e6bc4b)

I get the below error.

```
{
  "message": "unable to exec mysql table index statements: Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order);\n    END IF;\nEND;\n\nCALL NeosyncAddIndexIfNotExists();\nDROP PROCEDURE Neos' at line 12",
  "retryState": "MaximumAttemptsReached"
}
```

Once I then turn off the init schema option on `Destionation` and rerun the job - it completes fine.

However, if I make subsequent edits to the job transformer, like going from `passthrough` to `Transform First name` it completes, but does not execute the transform.

## How to reproduce

Unsure if this is related to my specific DB.

<sub>[NEOS-1311](https://linear.app/nucleus-cloud/issue/NEOS-1311/syntax-error-neosyncaddindexifnotexists)</sub>

**Comment by nickzelei** [comment]
Hey @b3nk3 - I was able to reproduce and fix the issue you were seeing with the Mysql init statements. 
There was a bug when we were initing sql indices, the table and columns were not being properly escaped (looks like you have a column called "orders" which is a reserved keyword in MySQL.

Anywho, that should be fixed now on `main`. It will be available in the `0.4.51` release, or is more immediately available via the `0.4.51-pre.26` pre-release tag.

Separately, I was not able to reproduce the what you mentioned about the job transformer. 

Steps I took:
1. Created new mysql->mysql job with all passthrough. Destination options: Truncate before insert, Init Table Schema
2. Triggered job run
3. Updated column from passthrough -> Transform First name, Saved form
4. Triggered second job run (column was updated with new data)
