### ISSUE TITLE
Dependency failed to start: container neosync-db exited 

### ISSUE THREAD

**Issue by cloudcompute** [nucleuscloud/neosync#2464]
## Bug description
Trying to run it locally using the make compose/up command. But the neosync-db container is not working.

## How to reproduce

1. make compose/up

## Environment
Linux Intel  64

**Comment by nickzelei** [comment]
Hi there, so sorry you ran into an issue here! Would you mind providing some more information, such as logs or anything else that is relevant?

I checked out main from within a linux container and run `make compose/up` and was able to stand everything up without issue, so I'm not able to reproduce this.

**Comment by cloudcompute** [comment]
Hi 

Sorry for the late response. I dowmloaded the contaier and it worked.

Thanks
