### ISSUE TITLE
[NEOS-1323] sub text is different font size for synthetic data sample description

### ISSUE THREAD

**Issue by evisdrenova** [nucleuscloud/neosync#2470]
![image.png](https://uploads.linear.app/a9c4e27b-39a0-41a6-a85a-a5e6b97b33a2/d90709b7-901d-41bf-9109-a6cded38cf19/fd38a5a7-0c78-4250-991e-e1f9eddfbeef?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2E5YzRlMjdiLTM5YTAtNDFhNi1hODVhLWE1ZTZiOTdiMzNhMi9kOTA3MDliNy05MDFkLTQxYmYtOTEwOS1hNmNkZWQzOGNmMTkvZmQzOGE1YTctMGM3OC00MjUwLTk5MWUtZTFmOWVkZGZiZWVmIiwiaWF0IjoxNzIzNjAxNjAzLCJleHAiOjE3NTUxMzc2MDN9.ht1fq4aPTlvQHIZpfZJGlAOsiteH_gtiAQ_CigZ7fhI)

<sub>From [SyncLinear.com](https://synclinear.com) | [NEOS-1323](https://linear.app/nucleus-cloud/issue/NEOS-1323/sub-text-is-different-font-size-for-synthetic-data-sample-description)</sub>

**Comment by frankie-mur** [comment]
Hey @evisdrenova , can I take a crack at this?

**Comment by evisdrenova** [comment]
@frankie-mur go for it! Let me know if you have any questions.
