### ISSUE TITLE
MySQL connection fails when password contains { character (and possibly other special characters)

### ISSUE THREAD

**Issue by kenzaboussaoud8** [nucleuscloud/neosync#2513]
## Bug description
We encountered a bug in the MySQL connection process where passwords containing special characters, specifically the { character, are not correctly escaped, causing connection failures. These passwords are automatically generated by AWS, so this might affect a lot of other users.

Error 1044 (42000): Access denied for user 'user'@'IP' to database 'db'

## How to reproduce

1. Generate a MySQL password that includes the { character (e.g., using AWS's automatic password generation feature).
2. Create a MYSQL connection to the db on the front app
3. Test connection

**Comment by nickzelei** [comment]
Fixed via #2511 .
