### ISSUE TITLE
[NEOS-1362] Add Github Action for testing the frontend

### ISSUE THREAD

**Issue by nickzelei** [nucleuscloud/neosync#2535]
We currently only need to test the `frontend/apps/web` folder.

We have a script in there so we can run `npm run test` which triggers jest.

We should add a section to our frontend github actions that triggers a test run.

<sub>From [SyncLinear.com](https://synclinear.com) | [NEOS-1362](https://linear.app/nucleus-cloud/issue/NEOS-1362/add-github-action-for-testing-the-frontend)</sub>

**Comment by faisalill** [comment]
@nickzelei Tried to fix this.
https://github.com/nucleuscloud/neosync/pull/2800
