### ISSUE TITLE
[NEOS-1555] update outdated screenshots in docs

### ISSUE THREAD

**Issue by evisdrenova** [nucleuscloud/neosync#2821]
we have a few places that have outdated screenshots that we need to update:

* [https://docs.neosync.dev/transformers/user-defined](https://docs.neosync.dev/transformers/user-defined) - 
  * the last screenshot is outdated and shows an older version of the schema page.
* [https://docs.neosync.dev/guides/creating-a-sync-job](https://docs.neosync.dev/guides/creating-a-sync-job) - 
  * the second screenshot is outdated and shows an older version of the Create a new job page
  * the screenshot on step 5 shows an older version of the schema page and should be updated
* [https://docs.neosync.dev/guides/creating-a-data-gen-job](https://docs.neosync.dev/guides/creating-a-data-gen-job)
  * the second screenshot is outdated and shows an older version of the Create a new job page
  * the screenshot on step 5 shows an older version of the schema page and should be updated

<sub>From [SyncLinear.com](https://synclinear.com) | [NEOS-1555](https://linear.app/nucleus-cloud/issue/NEOS-1555/update-outdated-screenshots-in-docs)</sub>

**Comment by danieltayal07** [comment]
<img width="1796" alt="Screenshot 2024-10-18 at 12 19 00 AM" src="https://github.com/user-attachments/assets/e73c7b39-5217-4447-afa6-7c0c19f656ca">
<img width="1800" alt="Screenshot 2024-10-18 at 12 22 58 AM" src="https://github.com/user-attachments/assets/d8b3de98-79b8-4beb-a86e-ca4f7fd9fc0c">
<img width="1799" alt="Screenshot 2024-10-18 at 12 25 23 AM" src="https://github.com/user-attachments/assets/3e00ee5e-1458-40ca-a5be-e3ab2f99eb08">
<img width="1800" alt="Screenshot 2024-10-18 at 12 28 19 AM" src="https://github.com/user-attachments/assets/7b412de8-0e94-4d1b-9048-0926bbc3d3bd">
<img width="1800" alt="Screenshot 2024-10-18 at 12 36 28 AM" src="https://github.com/user-attachments/assets/82e7682b-4617-4617-96a9-e28e9c98fb26">


are these ok?

**Comment by danieltayal07** [comment]
is they are ok i will make a pull request

**Comment by evisdrenova** [comment]
@danieltayal07 looks good!

**Comment by danieltayal07** [comment]
so now should i make a pull request, so that it can count in?

**Comment by evisdrenova** [comment]
yes please create a PR and i will review and comment/approve

**Comment by danieltayal07** [comment]
how should i put the png's 
like should i put the files screenshots outside itself or make a md?

**Comment by danieltayal07** [comment]
i made the pull request
i am sorry if i did it wrong, i'll fix it just a little guidance 🙏

**Comment by evisdrenova** [comment]
No problem - let me walk you through it. Here's what to do:

1. git clone the neosync repo down to your local machine. 
2. create a new pr using `git checkout -b updateDocsOldScreenshots`
3. add the images to the `neosync/docs/static/img` folder. You can just drag and drop them in there.
4. Update paths to those images in the docs pages that you updated. For example, you can find the `User Defined` file can be found at `neosync/docs/transformers/user-defined.md`
5. update the path from the current one `![udt](https://assets.nucleuscloud.com/neosync/docs/udt-schema-page.png)` to the new path `![schema-page](/img/<name-of-the-file>.png)`
6. add the changes to your branch with `git add .`
7. create a new commit `git commit -m 'updated old screenshots'`
8. push the changes the the repo `git push origin updateDocsOldScreenshots`

if you wanna walk through it together, lmk and we can jump on a discord call!

**Comment by danieltayal07** [comment]
i am not able to understand the 4th and 5th point how to change the paths, like i went in the user-defined.md and there i had to change the last link ![udt](https://assets.nucleuscloud.com/neosync/docs/udt-schema-page.png)

to the new path link, not able to write the new path link
help if possible
