### ISSUE TITLE
[NEOS-442] Update job status

### ISSUE THREAD

**Issue by evisdrenova** [nucleuscloud/neosync#780]
job status currently doesn't support enough states and map correctly to temporal. 

1. Remove status field from Jobs db table. 
2. Map Neosync status to temporal status (pauseStatus, scheduleStatus)
3. Update FE to support pause status and schedule status

<sub>From [SyncLinear.com](https://synclinear.com) | [NEOS-442](https://linear.app/nucleus-cloud/issue/NEOS-442/update-job-status)</sub>

**Comment by nickzelei** [comment]
Just going to kill this for now. The UI we have today makes this pretty clear that there is a different between scheduled and paused.

What we should do eventually is remove the extra job status states that we have defined in the proto.
