### ISSUE TITLE
[NEOS-451] Lists are not properly rendered in docs

### ISSUE THREAD

**Issue by nickzelei** [nucleuscloud/neosync#790]
Both ordered and unordered lists do not have a bullet or numbers rendered in them. 

We should fix this.

<sub>From [SyncLinear.com](https://synclinear.com) | [NEOS-451](https://linear.app/nucleus-cloud/issue/NEOS-451/lists-are-not-properly-rendered-in-docs)</sub>

**Comment by evisdrenova** [comment]
yeah idk why this happens, we might just have to make custom list components which isn't ideal - will investigate

**Comment by evisdrenova** [comment]
not even a custom <ol> component works…
