### ISSUE TITLE
[NEOS-469] Make transformer name column clickable in /transformers table

### ISSUE THREAD

**Issue by nickzelei** [nucleuscloud/neosync#812]
Might as well make all of the resources name clickable. most other tables have a uuid col and that is clickable.

<sub>From [SyncLinear.com](https://synclinear.com) | [NEOS-469](https://linear.app/nucleus-cloud/issue/NEOS-469/make-transformer-name-column-clickable-in-transformers-table)</sub>

**Comment by evoxf1** [comment]
May I look into this

**Comment by nickzelei** [comment]
> May I look into this

Sure! Most of the other tables in the app have the "id" column that is clickable.
The goal of this issue would be to make the transformer name column a link and it should route to the `/<account-name>/transformers/:id` page.

**Comment by nickzelei** [comment]
sounds great. I've assigned it to you, please let me know if you run into any troubles.

**Comment by evoxf1** [comment]
@nickzelei cool, thanks

**Comment by evoxf1** [comment]
hey @nickzelei  I am having problem running the repo locally, tried composing via docker still localhost:3000 is not reachable...

**Comment by evoxf1** [comment]
@nickzelei Hey Nick, I just wanna know if I am on the right track with the PR, need your feedback..

**Comment by nickzelei** [comment]
> @nickzelei Hey Nick, I just wanna know if I am on the right track with the PR, need your feedback..

left some comments on your PR.
