### ISSUE TITLE
[NEOS-522] Cloning a transformer should fill out form fields

### ISSUE THREAD

**Issue by nickzelei** [nucleuscloud/neosync#909]
Example:

When on `[http://localhost:3000/personal/transformers/systemTransformers/generate_email](http://localhost:3000/personal/transformers/systemTransformers/generate_email)`

As a user I click `Clone Transformer` button. I would expect this to take me to the clone page with certain fields pre-filled. However, this just takes me to the "new transformer" form.

---

We can accomplish this by just adding a query string to the button link with the system transformer's name.

Then the new transformer form can look for that and prefill the Select option, the name, and description.

The name we can do the classic `Name1` 

The description we can prefill the system transformer's description.

<sub>From [SyncLinear.com](https://synclinear.com) | [NEOS-522](https://linear.app/nucleus-cloud/issue/NEOS-522/cloning-a-transformer-should-fill-out-form-fields)</sub>

**Comment by faisalill** [comment]
@nickzelei 
I have made a PR for this issue.
